# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0559e86c1b79162b89c9dedf91dd717cbea43491cb598b0e343d22d6e401be198774335193277be273be358b9af8457a26d99d204ee408ec8b967e39e58b07b

test:
  secret_key_base: 6517c503a418846c5214c2966c6d455dbc1e90897e53b4d0143832333017b58c521404a3329724c43946129e8b432185aaeac59a27f9fdf8442c148ad236bf2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
